name: ts-classification-env
channels:
  - conda-forge
dependencies:
  - python=3.11.0
  - pip
  - pip:
      - jupyterlab==4.5.0
      - matplotlib==3.10.7
      - mlflow==3.6.0
      - tslearn
      - git+https://github.com/moment-timeseries-foundation-model/moment.git
      - notebook==7.5.0
      - optuna==4.6.0
      - pandas==2.3.3
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - seaborn==0.13.2
      - git+https://github.com/google-research/timesfm.git
      - torch==2.9.1
      - torch-summary==1.4.5
      - tqdm==4.67.1
      - transformers